<?php
require_once "./application/libraries/OAuth.php";

class Payments_model extends CI_Model 
{
	public function make_pesapal_payment2()
	{
		//pesapal params
		$token = $params = NULL;
		
		/*
		PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
		when you are ready to go live change to https://www.pesapal.com.
		*/
		$consumer_key = '1VsCbDt7UgL7tiZMjXnea8TX3vRb/Lcj';//Register a merchant account on
						   //demo.pesapal.com and use the merchant key for testing.
						   //When you are ready to go live make sure you change the key to the live account
						   //registered on www.pesapal.com!
		$consumer_secret = '7PxQd2Zei6z/SlrqyMW5gUm8QvQ=';// Use the secret from your test
						   //account on demo.pesapal.com. When you are ready to go live make sure you 
						   //change the secret to the live account registered on www.pesapal.com!
		//$this->load->model('OAuthSignatureMethod_HMAC_SHA1');
		$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
		$iframelink = 'http://pesapal.com/api/PostPesapalDirectOrderV4';//change to      
						   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
		
		//get form details
		$amount = $_POST['amount'];
		$amount = number_format($amount, 2);//format amount to 2 decimal places
		
		$desc = $_POST['description'];
		$type = $_POST['type']; //default value = MERCHANT
		$reference = $_POST['reference'];//unique order id of the transaction, generated by merchant
		$first_name = $_POST['first_name'];
		$last_name = $_POST['last_name'];
		$email = $_POST['email'];
		$phonenumber = '';//ONE of email or phonenumber is required
		
		$callback_url = site_url(); //redirect url, the page that will handle the response from pesapal.
		
		$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);
		
		$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
		
		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);
		return $iframe_src;
		//display pesapal - iframe and pass iframe_src
		
	}
	
	public function make_pesapal_payment($flight_id)
	{
		//$api = 'http://demo.pesapal.com';
		$api = 'https://www.pesapal.com';
	
		$token = $params 	= NULL;
		$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';
		
		//Kenyan keys
		$consumer_key 		= "1VsCbDt7UgL7tiZMjXnea8TX3vRb/Lcj"; //fill key here
		$consumer_secret 	= "7PxQd2Zei6z/SlrqyMW5gUm8QvQ="; //fill secret here
		 
		$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
		$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);
		
		//get form details
		/*if(!$_POST['reference']){
			$ref				=  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',5);
			$_POST['reference']	=  substr(str_shuffle($ref),0,10);
		}*/
		
		//save visitor
		$data = array
		(
			'visitor_first_name' => $_POST['first_name'],
			'visitor_last_name' => $_POST['last_name'],
			'visitor_email' => $_POST['email'],
			'visitor_phone' => $_POST['phone_number'],
			'visitor_type_id' => 1
		);
		
		$this->db->insert('visitor', $data);
		$visitor_id = $this->db->insert_id();
		
		//save booking
		$data2 = array
		(
			'visitor_id' => $visitor_id,
			'booking_date' => date('Y-m-d'),
			'flight_id' => $flight_id,
			'traveller_type_id' => 1
		);
		
		$this->db->insert('booking', $data2);
		$booking_id = $this->db->insert_id();
		
		$amount = $_POST['amount'] * $_POST['seats'];
		
		$amount 		= str_replace(',','',$amount); // remove thousands seperator if included
		$amount 		= number_format($amount, 2); //format amount to 2 decimal places
		$desc 			= $_POST['description'];
		$type 			= 'MERCHANT';	
		$first_name 	= $_POST['first_name'];
		$last_name 		= $_POST['last_name'];
		$email 			= $_POST['email'];
		$phonenumber	= $_POST['phone_number'];
		$currency 		= "USD";//$_POST['currency'];
		$reference 		= $booking_id;// $_POST['reference']; //unique transaction id, generated by merchant.
		$callback_url 	= site_url().'payment';//'http://localhost/pbf/demo/redirect.php'; //URL user to be redirected to after payment
		
		//Record order in your database.
		/*$database = new pesapalDatabase();
		$database->store($_POST);*/ 
			
		$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
					   <PesapalDirectOrderInfo 
							xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
							xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
							Currency=\"".$currency."\" 
							Amount=\"".$amount."\" 
							Description=\"".$desc."\" 
							Type=\"".$type."\" 
							Reference=\"".$reference."\" 
							FirstName=\"".$first_name."\" 
							LastName=\"".$last_name."\" 
							Email=\"".$email."\" 
							PhoneNumber=\"".$phonenumber."\" 
							xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);
		
		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);
		return $iframe_src;
	}
}
?>