<?php
require_once "./application/libraries/OAuth.php";

class Payments_model extends CI_Model 
{	
	public function make_pesapal_payment($flight_id)
	{
		//$api = 'http://demo.pesapal.com';
		$api = 'https://www.pesapal.com';
	
		$token = $params 	= NULL;
		$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';
		
		//Kenyan keys
		$consumer_key 		= "1VsCbDt7UgL7tiZMjXnea8TX3vRb/Lcj"; //fill key here
		$consumer_secret 	= "7PxQd2Zei6z/SlrqyMW5gUm8QvQ="; //fill secret here
		 
		$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
		$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);
		
		//get form details
		/*if(!$_POST['reference']){
			$ref				=  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',5);
			$_POST['reference']	=  substr(str_shuffle($ref),0,10);
		}*/
		
		//save visitor
		$data = array
		(
			'visitor_first_name' => $_POST['first_name'],
			'visitor_last_name' => $_POST['last_name'],
			'visitor_email' => $_POST['email'],
			'visitor_phone' => $_POST['phone_number'],
			'visitor_type_id' => 1
		);
		
		$this->db->insert('visitor', $data);
		$visitor_id = $this->db->insert_id();
		
		if($_POST['booking_type'] == 1)
		{
			$amount = $_POST['amount'];
			$seats = $_POST['seats'];
		}
		
		else
		{
			//get charter plane price
			$this->db->where('flight_id = '.$flight_id);
			$query = $this->db->get('flight');
			$row = $query->row();
			$amount = $row->charter_plane_price;
			$seats = 1;
		}
		
		//save booking
		$data2 = array
		(
			'visitor_id' => $visitor_id,
			'booking_amount' => $amount,
			'booking_units' => $seats,
			'additional_info' => $this->input->post('additional_info'),
			'flight_id' => $flight_id,
			'traveller_type_id' => 1
		);
		
		$this->db->insert('booking', $data2);
		$booking_id = $this->db->insert_id();
		
		//save passengers
		$total_passengers = count($this->input->post('passenger_first_name'));
		
		for($r = 0; $r < $total_passengers; $r++)
		{
			$passenger_first_name = $this->input->post('passenger_first_name');
			$passenger_last_name = $this->input->post('passenger_last_name');
			$passenger_nationality = $this->input->post('passenger_nationality');
			$passenger_passport_no = $this->input->post('passenger_passport_no');
			
			$passenger_data = array
			(
				'booking_id' => $booking_id,
				'booking_passenger_first_name' => $passenger_first_name[$r],
				'booking_passenger_last_name' => $passenger_last_name[$r],
				'booking_passenger_nationality' => $passenger_nationality[$r],
				'booking_passenger_passport' => $passenger_passport_no[$r]
			);
			$this->db->insert('booking_passenger', $passenger_data);	
		}
		/*if (is_array($ownerNames)) {
			foreach ($ownerNames as $ownerName => $k) {
				echo "Owner Name is : " . $k . "<br/>";
			}
		}
		else {
			echo "Owner is not array";
		}*/
		
		$amount = $amount * $seats;
		
		$amount 		= str_replace(',','',$amount); // remove thousands seperator if included
		$amount 		= number_format($amount, 2); //format amount to 2 decimal places
		$desc 			= $_POST['description'];
		$type 			= 'MERCHANT';	
		$first_name 	= $_POST['first_name'];
		$last_name 		= $_POST['last_name'];
		$email 			= $_POST['email'];
		$phonenumber	= $_POST['phone_number'];
		$currency 		= "USD";//$_POST['currency'];
		$reference 		= $booking_id;// $_POST['reference']; //unique transaction id, generated by merchant.
		$callback_url 	= site_url().'payment';//'http://localhost/pbf/demo/redirect.php'; //URL user to be redirected to after payment
		
		//Record order in your database.
		/*$database = new pesapalDatabase();
		$database->store($_POST);*/ 
			
		$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
					   <PesapalDirectOrderInfo 
							xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
							xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
							Currency=\"".$currency."\" 
							Amount=\"".$amount."\" 
							Description=\"".$desc."\" 
							Type=\"".$type."\" 
							Reference=\"".$reference."\" 
							FirstName=\"".$first_name."\" 
							LastName=\"".$last_name."\" 
							Email=\"".$email."\" 
							PhoneNumber=\"".$phonenumber."\" 
							xmlns=\"http://www.pesapal.com\" />";
		$post_xml = htmlentities($post_xml);
		
		//post transaction to pesapal
		$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
		$iframe_src->set_parameter("oauth_callback", $callback_url);
		$iframe_src->set_parameter("pesapal_request_data", $post_xml);
		$iframe_src->sign_request($signature_method, $consumer, $token);
		return $iframe_src;
	}
}
?>